_wandb:
    value:
        cli_version: 0.21.1
        e:
            4d1s912hkk25c9zgeljgxu7beu8mdepp:
                codePath: simple_test.py
                codePathLocal: simple_test.py
                email: ashish.biswas@gmail.com
                executable: /home/ashish/.pyenv/versions/3.10.11/bin/python
                git:
                    remote: https://github.com/ashishrb/gpt-oss-20b-ft.git
                host: ashish-MS-7E59
                os: Linux-6.14.0-27-generic-x86_64-with-glibc2.41
                program: /mnt/data_storage/git_projects/oss-20b-ft/simple_test.py
                python: CPython 3.10.11
                root: /mnt/data_storage/git_projects/oss-20b-ft
                startedAt: "2025-08-15T07:21:03.349530Z"
                writerId: 4d1s912hkk25c9zgeljgxu7beu8mdepp
        m: []
        python_version: 3.10.11
        t:
            "1":
                - 1
                - 49
                - 51
            "2":
                - 1
                - 49
                - 51
            "3":
                - 2
                - 13
            "4": 3.10.11
            "5": 0.21.1
            "12": 0.21.1
            "13": linux-x86_64
